{
   "apps": [ {
      "appid": "ExtBank",
      "apptype": 1,
      "enabled": true,
      "loadtype": 1,
      "showstyle": 1
   }, {
      "appid": "KantuHistory",
      "apptype": 1,
      "enabled": true,
      "loadtype": 1,
      "showstyle": 1
   }, {
      "appid": "ExtVideoGallery",
      "apptype": 1,
      "enabled": true,
      "loadtype": 1,
      "showstyle": 1
   }, {
      "appid": "Translator",
      "apptype": 1,
      "enabled": true,
      "loadtype": 0,
      "showstyle": 1
   }, {
      "appid": "ExtWebmail",
      "apptype": 1,
      "enabled": true,
      "loadtype": 1,
      "showstyle": 2
   }, {
      "appid": "ExtFeedWeibo",
      "apptype": 1,
      "enabled": true,
      "loadtype": 1,
      "showstyle": 2
   }, {
      "appid": "ExtYouxi",
      "apptype": 1,
      "enabled": true,
      "loadtype": 1,
      "showstyle": 1
   }, {
      "appid": "SnapPlugin",
      "apptype": 1,
      "enabled": true,
      "loadtype": 1,
      "showstyle": 1
 